$(document).ready(function(){
	var quoteSource=[

{quote: "My system is to make him thirsty, so he'll volunteer to drink.", name:"Myles Horton", hypo:"https://via.hypothes.is/http://impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf#annotations:hm4emLwPEeaB_X-KI_tI-Q"},
{quote: "the delicate relationship between teaching, giving knowl­edge, and learning knowledge", name:"Third Party", hypo:"https://hyp.is/x0FsmrwPEea_vw_cGLM_5Q/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "I think it's my responsi­bility to share what I believe in, not only in discussions but in the way I live and in the way the workshops run and in the way Highlander's run, the way life is.", name:"Myles Horton", hypo:"https://hyp.is/x0FsmrwPEea_vw_cGLM_5Q/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "The central meeting room at Highlander is circular in shape. Rock­ing chairs, a fireplace, and a spectacular view of the Smoky Mountains provide a comfortable atmosphere for workshops.", name:"Editor's Note", hypo:"https://hyp.is/8TEKkrwPEean9vMRevL4cQ/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "Starting from people's experiences, and not from our understanding of the world, does not mean that we don't want the people to come with us in order to go beyond us afterward", name:"Paulo Freire", hypo:"https://hyp.is/VRzs4rwQEea_wbOMPm5tIg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "the quality of becoming more and more open to feel the feelings of others, to become so sensitive that we can guess what the group or one person is thinking at that moment.", name:"Paulo Freire", hypo:"https://hyp.is/Yd3i4rwQEeaCAPOL705ezQ/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "they come absolutely convinced that the teacher has to give a class to them", name:"Paulo Freire", hypo:"https://hyp.is/czIiurwQEeaUHKdSNad3tQ/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "You set the stage for doing something that they're uncomfortable with. You know they're uncomfortable with it, and you have to work through that business of getting them to be comfortable with trusting them­selves a little bit, trusting their peers a little bit", name:"Myles Horton", hypo:"https://hyp.is/hBa7QLwQEea9V68TNpBvQQ/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "then they begin to see that you aren't going to play the role of an expert, except in the sense that you are the expert in how they're going to learn, not in what they're going to learn.", name:"Myles Horton", hypo:"https://hyp.is/lD3k5LwQEearAAdr0e759Q/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "close enough to their expectation... You have to make concessions like that.", name:"Myles Horton", hypo:"https://hyp.is/phqb2rwQEea1PKNI538Ozw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "The more people partici­pate in the process of their own education, the more the people participate in the process of defining what kind of production to produce, and for what and why, the more the people participate in the development of their selves.", name:"Paulo Freire", hypo:"https://hyp.is/SKY6iLwTEeaPmkMMa5-oTg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "That was what they wanted. Now what we wanted in addition to that was to help them understand that they should work with a larger community. They should work with farmers, they should deal with integration, they should be part of the world. We had our own agenda.", name:"Myles Horton", hypo:"https://hyp.is/unwhXLwQEeajTHeHliodDQ/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "They had to learn to think, make decisions-not learn gimmicks, not learn techniques, but learn how to think.", name:"Myles Horton", hypo:"https://hyp.is/w0sL_rwQEeasVFdpQMencw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "You've gotta have a structure that participants can feel comfortable with until they begin to have something to deviate from or add to.", name:"Myles Horton", hypo:"https://hyp.is/3UguiLwQEeasVq8fHeh6KQ/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "So we turned it all over to them, and they were in complete control. I mean they exercised that control.", name:"Myles Horton", hypo:"https://hyp.is/0huzBLwQEeasVauaQOoADA/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "It takes the power of everyone united to get a grievance settled.", name:"Myles Horton", hypo:"https://hyp.is/7uy1lrwQEea1PbMlJpPNiQ/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "No matter where this kind of educator works, the great difficulty­or the great adventure!-is how to make education something which, in being serious, rigorous, methodi­cal, and having a process, also creates happiness and joy.", name:"Paulo Freire", hypo:"https://hyp.is/OTkjgrwREea1Pq_Zv7YYdA/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "This transforms the practice of education into a kind of entertainment.", name:"Paulo Freire", hypo:"https://hyp.is/Sis8NLwREeaUHk_ljuYy-w/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "it's impossible for me in this kind of education to teach how to think unless. we are teaching something, some content to the students.", name:"Paulo Freire", hypo:"https://hyp.is/Xic7jrwREearAqfQMhASXQ/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "What Myles did was to touch their memory about a subject and to remake the road. I think that it's really impossible to teach how to think more critically by just making a speech about criti­cal thought", name:"Paulo Freire", hypo:"https://hyp.is/bjeAnLwREeaPlQe2alaCWw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "I mean what I'm doing with the mind is the same as nature does with the body. It's no different. I think you should stretch people to their limits and our limits", name:"Myles Horton", hypo:"https://hyp.is/hEx1SrwREeap5lP4gkf4qA/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "Money has to come from the system, and people that we identify with produce that wealth.", name:"Myles Horton", hypo:"https://hyp.is/mGu1hrwREeaPlovefqsg9A/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "If I believe in social equality and don't practice it, then what I say is hollow. You have to have that kind of consis­tency.", name:"Myles Horton", hypo:"https://hyp.is/oz4wTLwREea3nlOk9GvCDg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "You have to tie the practical with the visionary.", name:"Myles Horton", hypo:"https://hyp.is/s1wHVrwREeaKWicR4PmOhw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "I think if I had to put a finger on what I consider a good education, a good radical education, it wouldn't be anything about methods or techniques. It would be loving people first.", name:"Myles Horton", hypo:""},
{quote: "next is respect for people's abilities to learn and to act and to shape their own lives.", name:"Myles Horton", hypo:"https://hyp.is/wlpFELwREeade1sJ_lrVAw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "The third thing grows out of caring for people and having respect for people's ability to do things, and that is that you value their experiences.", name:"Myles Horton", hypo:"https://hyp.is/zuzJELwREeajTWsJ3laNmg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "Highlander can't be described as an organization because it isn't departmen­talized and mechanistically conceived. It's more of an organism, therefore it's hard to describe. It's a mosaic or a piece of weaving.", name:"Myles Horton", hypo:"https://hyp.is/35Af7LwREea_xHtq4gX0qg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "Highlander is a kind of a weaving of many colors, some blend and some clash, but you know it's alive.", name:"Myles Horton", hypo:"https://hyp.is/7IxiMrwREeaPJK8YrNPCpQ/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "Movements change what goes on and how things are organized.", name:"Myles Horton", hypo:"https://hyp.is/_a2H7rwREealivsixLBY5A/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "We were part of the world but we had to start locally.", name:"Myles Horton", hypo:"https://hyp.is/DTLlsLwSEeaPlyfmn16XUw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "Authority is necessary to the educational process as well as necessary to the freedom of the stu­dents and my own. The teacher is absolutely necessary. What is bad, what is not necessary, is authoritarianism, but not authority.", name:"Paulo Freire", hypo:"https://hyp.is/HgTMALwSEea3n4ONXOgWfA/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "The teacher is of course an artist, but being an artist does not mean that he or she can make the profile, can shape the students. What the educator does in teaching is to make it possible for the students to be­come themselves.", name:"Paulo Freire", hypo:"https://hyp.is/L5IolrwSEeasWmPlkjudzA/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "The people who use that label are people who unknowingly, for the most part, are dedicated to the support of the status quo.", name:"Myles Horton", hypo:"https://hyp.is/QoIRALwSEea3oItrY-fnYg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "I'm just saying that we understand that the people who claim to be neutral, and call us propagandists because we are not neutral, are not neutral either. They're just ignorant. They don't know that they're supporters of the status quo. They don't know that that's their job. They don't know that the institution is dedicated to per­petuating a system and they're serving an institution. They have influence nevertheless.", name:"Myles Horton", hypo:"https://hyp.is/UgWmWrwSEeaOwMsG3QYhog/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "Conflicts are the midwife of consciousness.", name:"Paulo Freire", hypo:"https://hyp.is/YQ9SVLwSEeajT1tEVn_5jg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "Those who come tomor­row will start acting, precisely taking what we did as the starting point.", name:"Paulo Freire", hypo:"https://hyp.is/cL54krwSEeaPmH__uR1MvA/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "I think it is abso­lutely indispensable that educators be secure, capable, and have a capacity for loving and for curiosity.", name:"Paulo Freire", hypo:"https://hyp.is/fMytXLwSEeaOweN5JnE6BQ/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "I have noth­ing against teaching. But I have many things against teaching in an authoritarian way.", name:"Paulo Freire", hypo:"https://hyp.is/iFrA5rwSEea1P8sC7oJbTg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "knowledge never is static. It's always in the process.", name:"Paulo Freire", hypo:"https://hyp.is/k80E6LwSEea3oueLZ40ncg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "I am humble because I am incomplete", name:"Paulo Freire", hypo:"https://hyp.is/ndZ35LwSEea_xYeQ3Fkn8g/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "one of the virtues we have to create in ourselves as progressive educators is the virtue of humility.", name:"Paulo Freire", hypo:"https://hyp.is/qre6zLwSEean-fugkdtF9w/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "I try to find ways to expose them to learning processes that would finally lead them to take a look at my conclusion.", name:"Myles Horton", hypo:"https://hyp.is/v2yU7LwSEeasnJfyRrFlmw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "MYLES: Well I think you have to divide that into principles. When I say what I believe, I'm talking about prin­ciples such as love and democracy, where people control their Jives. THIRD PARTY: Your vision. MYLES: My vision. Now the strategy for my vision, the ap­proaches and processes, I've learned from other people.", name:"Myles Horton", hypo:"https://hyp.is/1vyQ2rwSEeaPmedF5V5cjw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "any kind of prob­lem has five or six good solutions and five or six bad solutions.", name:"Myles Horton", hypo:"https://hyp.is/5_Ep3LwSEea27M_ofhuIgA/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "If you have a convic­tion, you have a responsibility to act on that conviction where you can, and if you're doing education, you act on it in an educational context.", name:"Myles Horton", hypo:"https://hyp.is/GxDwVLwTEealiyNK9iSBTg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "For me it has always been a political question, not exclusively an edu­cational question, at what levels students take part in the process of organizing the curriculum.", name:"Paulo Freire", hypo:"https://hyp.is/MwKquLwTEeaOw0dkEGoM5w/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_Chapter_4.pdf"},
{quote: "being a pro­gressive on one hand does not mean to be naive, but to make some decisions and then to risk the preservation of the revolution. On the other hand, being a progres­sive means to deepen the connection with the masses of people, means to respect the beliefs of the people, means to consult the people, means to start from the letters and words with which the people are starting the process of education.", name:"Paulo Freire", hypo:"https://hyp.is/MlWjbMAkEea15JNh90EZqA/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "Then, through this kind of very strong serious work, through a work that is at the same time tender and heavy and serious and rigorous, we need to shape, to reshape, to form permanently the teachers without manipulating them.", name:"Paulo Freire", hypo:"https://hyp.is/G0ZKgsAkEea9U39p88lzCA/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "But understanding formation not as some­thing that we do in some weekends or some semesters, but formation as a permanent process, and formation as being an exercise, a critical understanding of what we do.", name:"Paulo Freire", hypo:"https://hyp.is/_HBz2sAjEea2SyN6kipJvg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "I don't like the word training in English. Maybe it's a prejudice of mine, but I prefer formation, formation in French and formação in Portuguese.", name:"Paulo Freire", hypo:"https://hyp.is/6rFd0MAjEeasHtPRyiRdqQ/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "We must be free; we must be free to believe in freedom. Do you see this paradox? Without freedom it's difficult to understand freedom. On the other hand, we fight for freedom to the extent that we don't have freedom, but in fighting for freedom we discover how freedom is beautiful and difficult to be created, but we have to believe that it's possible.", name:"Paulo Freire", hypo:"https://hyp.is/1Fq1uMAjEeaZFs-xQNRoiA/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "We are afraid of risking. And it's impossible, just impossible, to create without risk­ing. It's absolutely impossible, but it takes time to begin to risk", name:"Paulo Freire", hypo:"https://hyp.is/xeZD5MAjEeaRUhsgrylJSg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "When I talked with the presi­dent, he used to say to me, ", name:"Paulo Freire", hypo:"https://hyp.is/seCfXMAjEeaPL8vglxs0fw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "There are many ghosts in society fighting against the dream of a much more open society", name:"Paulo Freire", hypo:"https://hyp.is/mQkA8MAjEeaVDRNnNZensg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "if we could do something over­night, it's not worth doing because if it's that simple and that easy, it'll take care of itself.", name:"Myles Horton", hypo:"https://hyp.is/g9599MAjEeaZFSOawBj29Q/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "the deepened transformation in society never arrived on a second Monday morning. Never. No, the radical transformation of society is a process, really, and it comes like this.", name:"Paulo Freire", hypo:"https://hyp.is/XcYHLMAjEeaX2RslONhdXQ/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "It means to be patient, or the words I prefer, to be impatiently patient, in the process of struggling to change.", name:"Paulo Freire", hypo:"https://hyp.is/Pd8lJMAjEeaX2Ov0C9q5Sg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "It is a center that wants to be a theoretical context inside of which the workers can make a critical reflection about what they do outside of the theoretical context.", name:"Paulo Freire", hypo:"https://hyp.is/LmArmMAjEea28puwFvpE4w/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "The people in Nicara­gua are helping us in Brazil, are helping us as Latin Americans, and are helping you to the extent that you are also helping them. This is kind of a struggle here; on the one hand, you gave support to Nicaragua. On the other hand, you made an impression in the space inside of the country, do you see, and this is history.", name:"Paulo Freire", hypo:"https://hyp.is/4OtCRMAiEea28Rf67whBkw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "Trying to co-opt is a kind of a struggle on behalf of those who have power to do so. It's a tac­tic; it's a moment of the struggle.", name:"Paulo Freire", hypo:"https://hyp.is/vy0PUsAiEea2SesNZpIrmw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "Does success mean that we're no longer subver­sive enough?", name:"Paulo Freire", hypo:"https://hyp.is/q9wWyMAiEeaZE5P5fSoYNA/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "So the phrase I've always used when I talk is, ", name:"Paulo Freire", hypo:"https://hyp.is/lEERCMAiEea9UdeNmyJzwg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "We have more space outside the system, but we also can create the space in­side of the subsystem or the schooling system in order to occupy the space. That is, I think politically, every time we can occupy some position inside of the subsystem, we should do so.", name:"Paulo Freire", hypo:"https://hyp.is/N3fMeMAiEeaqGQd-iGouSA/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "if you worked outside the system, you couldn't influence the system. The argument was that you could change the system. We concluded that reform within the sys­tem reinforced the system, or was co-opted by the system. Reformers didn't change the system, they made it more palatable and justified it, made it more humane, more intelligent", name:"Myles Horton", hypo:"https://hyp.is/FiPC_MAiEeaVC4euyhOokg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "Start with what they know. Build with what they have. But the best of leaders when the job is done, when the task is accomplished, the people will all say we have done it ourselves.", name:"Lao Tzu, 604 B.C.", hypo:"https://hyp.is/AwooIMAlEeaSZGvCTw0RTw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "It's necessary to laugh with the people because if we don't do that, we cannot learn from the people, and in not learning from the people we cannot teach them.", name:"Paulo Freire", hypo:"https://hyp.is/58S7_MAkEea90gdZ1v6Wjw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "I remember that my mother used to say to me, after the death of my father, that my father always said to her, ", name:"Paulo Freire", hypo:"https://hyp.is/0j9CrMAkEeaqGg8dyGCYzw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "I learned when I was a child that a loving space is indispensable for development of the children.", name:"Paulo Freire", hypo:"https://hyp.is/wRKRjMAkEea9VUd4Lui8OQ/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "The more we get this kind of alive love among parents, the more it's possible to help kids to grow up in good shape.", name:"Paulo Freire", hypo:"https://hyp.is/qOWV8MAkEeaOeJdsUiPYSg/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "I'm much better at working out ideas in action than I am in theorizing about it and then transferring my thinking to action.", name:"Myles Horton", hypo:"https://hyp.is/kKbs0sAkEeaZMr9mkeDk3g/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"},
{quote: "Those who refuse to share their knowledge with other people are making a great mistake, because we need it all.", name:"Myles Horton", hypo:"https://hyp.is/esmGGMAkEea78HejIWtPJw/impedagogy.com/wp/wp-content/uploads/2016/12/Myles_Horton_Paulo_Freire_We_Make_the_Road_by_W_Ch_5__6.pdf"}
];


	$('#quoteButton').click(function(evt){
		//define the containers of the info we target
		var quote = $('#quoteContainer p').text();
		var quoteGenius = $('#quoteGenius').text();
		//prevent browser's default action
		evt.preventDefault();
		//getting a new random number to attach to a quote and setting a limit
		var sourceLength = quoteSource.length;
		var randomNumber= Math.floor(Math.random()*sourceLength);
		//set a new quote
		for(i=0;i<=sourceLength;i+=1){
		var newQuoteText = quoteSource[randomNumber].quote;
		var newQuoteGenius = quoteSource[randomNumber].name;
		var newQuoteHypo = quoteSource[randomNumber].hypo;
		//console.log(newQuoteText,newQuoteGenius);
		var timeAnimation = 500;
		var quoteContainer = $('#quoteContainer');
		//fade out animation with callback
		quoteContainer.fadeOut(timeAnimation, function(){
			quoteContainer.html('');
			quoteContainer.append('<p>'+newQuoteText+'</p>'+'<p id="quoteGenius">'+'-								'+newQuoteGenius+'</p>'+'<p><a href="'+newQuoteHypo+'">Read this passage</a></p>');

			//fadein animation.
			quoteContainer.fadeIn(timeAnimation);
		});

		break;
	};//end for loop

});//end quoteButton function


});//end document ready
